#!/bin/bash
file=$1
shift
if [[ $file == "-"* ]]
then
  opt=$file
  file=$1
  shift
fi
export ARGV0=$file
if [[ $opt == "-DJSCAD_" ]]
then
  gcc $opt -E -x c -nostdinc $file | grep -v "^#"  > x.jscad
else
  gcc $opt -E -x c -nostdinc $file | grep -v "^#"  | nodejs - $*
fi
