#!/bin/bash
gcc -E -x c -nostdinc $1 | grep -v "^#" > /tmp/rpylint
pylint --docstring-min-length=100 --argument-naming-style=any --variable-naming-style=any --attr-naming-style=any --function-naming-style=any --class-naming-style=any --const-naming-style=any --min-public-methods=0 --max-args=8 /tmp/rpylint | grep -v "W0621: Redefining name '.*' from outer scope"
